---
title: "Dropped_Stats"
output: html_document
date: "2023-01-27"
desc: This file is created for analysis of dropped frames versus vEMG for EMBC2023

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r including libraries}
library(magrittr); library(here); library(janitor)
library(readxl); library(tidyverse)
library(knitr)
library(rmdformats)
library(Epi)
library(vcd)
library(broom)
library(patchwork)
library(vcd)
library(dplyr)
library(ggplot2)
```



```{r}
set.seed(431001)
# use set.seed to ensure that we all get the same random sample # of 1,000 NHANES subjects in our nh_data collection
nh_dat1 <- sample_n(NHANES, size = 1000) %>% select(ID, Gender, Age, Height)
nh_dat2 <- nh_dat1 %>% filter(complete.cases(Age, Height))
summary(nh_dat2)
nh_dat2 <- nh_dat1 %>%
rename(Sex = Gender) %>% filter(complete.cases(Age, Height))

 ggplot(data = nh_dat1, aes(x = Age, y = Height, color = Gender)) + geom_point() +
labs(title = "Height-Age Relationship in NHANES sample", y = "Height in cm.")
```

```{r read the file } 

dt <- read_csv("dropped_stats.csv",show_col_types = FALSE)
spec(dt)

```

This table is created using MATLAB making sure that there is no NAN, missing or infinite sample of any variable
```{r Modifying  the data types}
dt<-dt%>%mutate(Filt_Type = as.factor(Filt_Type),
                   Repeat = as.factor(Repeat),
                     Feat = as.factor(Feat),
                     Test = as.factor(Test),
                     Frame = as.integer(Frame))
dt
```


```{r plotting using facets}

plot<-filter(dt ) %>% select( c(Frame_Val, Filt_Type, Dropped,Frame,Test,MVC_Voli) )  

ggplot(data = plot, aes(x = Frame, y = 1000*Frame_Val, color = Filt_Type)) + 
geom_point() + geom_smooth(method = "loess") +facet_wrap(Test ~ MVC_Voli)+
labs(title = "EMG MAV Values", y = "MAV (mV)")
   

```

```{r Normality Checks 1- by violing plots}
MVCVoli10<- filter(plot, MVC_Voli=='10%')
test_jan7<- filter(plot, Test=='jan12',MVC_Voli=='30%')

ggplot(test_jan7, aes(x = Filt_Type, y = Frame_Val, fill = Filt_Type)) + geom_violin() +
scale_fill_viridis_d() + geom_boxplot(width = 0.3, fill = "white") +
guides(fill = FALSE) +
labs(title = "Boxplot of Temperature Drop in Sepsis Patients",
x = "", y = "Drop in Temperature (degrees C)") + coord_flip() +
theme_bw()

```

```{r Nomality Checks 2-Histogram}

ggplot(test_jan7, aes(x = Frame_Val, fill = Filt_Type, color = Filt_Type)) + geom_histogram(bins = 20) +
scale_fill_viridis_d() +
scale_color_viridis_d(direction = -1) +
guides(fill = FALSE, color = FALSE) +
labs(title = "Histograms of Temperature Drop in Sepsis Patients",
x = "Drop in Temperature (degrees Celsius") + theme_bw() +
facet_wrap(~ Filt_Type)

```

```{r Normality Checks 4- Density Ridges}

ggplot(test_jan7, aes(x = Frame_Val, y = Filt_Type, fill = Filt_Type)) + ggridges::geom_density_ridges(scale = 0.9) +
guides(fill = FALSE) +
labs(title = "Temperature Drop in Sepsis Patients",
x = "Drop in Temperature (degrees Celsius)", y = "") + ggridges::theme_ridges()

```

```{r Normality Checks 3-QQ Plots}

ggplot(test_jan7, aes(sample = Frame_Val)) + geom_qq() + geom_qq_line(col = "red") + theme_bw() +
facet_wrap(~ Filt_Type) +
labs(y = "Temperature Drop Values (in degrees C)")

```

