---
title: "Dropped_Stats"
output: html_document
date: "2023-01-27"
desc: This file is created for analysis of dropped frames versus vEMG for EMBC2023
# theme: darkly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r including libraries, display = FALSE}
library(magrittr); library(here); library(janitor)
library(readxl); library(tidyverse)
library(rmdformats)
library(Epi)
library(vcd)
library(broom)
library(patchwork)
library(vcd)
library(dplyr)
library(ggplot2)
```


```{r Data Inject } 

df <- read_csv("dropped_stats2.csv",show_col_types = FALSE)
#df<-df %>% mutate(Drp_Order = replace_na(Drp_Order, 0))

df<-df%>%mutate(Filt_Type = as.factor(Filt_Type),
                Repeat = as.factor(Repeat),
                Feat = as.factor(Feat),
                Test = as.factor(Test),
                MVC_Voli = as.factor(MVC_Voli),
                MVC_Stim = as.factor(MVC_Stim),
                Frame = as.integer(Frame),
                Drp_Order = as.factor(Drp_Order),
                Trial = as.factor(Trial))
summary(df)
df
```

```{r data frame modifications }



df<-df%>%mutate(Drp_Order=recode(Drp_Order,
                                '1' = '1st_Dropped',
                                '2' = '2nd_Dropped',
                                '3' = '3rd_Dropped',
                                '4' = '4th_Dropped',
                                'NonDropped' = 'NonDropped'))

summary(df)
```

# Mean percent difference of filters based on norm. values:

$\sum_{i=1}^{I=10} \frac{1}{I}\frac{MAV_{D,i}-MAV_{F,i}}{MAV_{D,i}}\times100$



```{r Plotting the dropped-frames }

tests <- c("mar7", "mar16",'feb27')
filt='GS'
reps=c('Rep_1','Rep_2','Rep_3')

TestString<-""
for (iTest in 1:length(tests)) 
{
  TestString<-sprintf("%s, %s",TestString, tests[iTest])
}

RepString<-""
for (iTest in 1:length(reps)) 
{
  RepString<-sprintf("%s, %s",RepString, reps[iTest])
}

SubTitleString<-sprintf("Tests: %s | Repeats: %s | Filter: %s | Dropped Frames are not Filtered" ,TestString,RepString,filt)
plot_df<-filter(df, Test==tests )
plot_df<-filter(plot_df,  Repeat==reps & Filt_Type==filt |Filt_Type=='Dropped' )

summary(plot_df)

#pdf("figures/4dropped3.pdf")

plt<-ggplot(plot_df, aes(x = Frame, y = Norm_Val, color = Drp_Order)) +
    geom_point() + #size = 1.2, alpha = 0.6
    geom_line(data= filter(df,Repeat=="Rep_1" & Filt_Type==c("Unfilt")), aes(x = Frame, y = Target*5, color = "Target (a.u.)")) +
    geom_segment(aes(x = 350, y = 1, xend = 525, yend = 1, color='Avg. 0-Stim Level'))+
    geom_segment(aes(x = 525, y = 0.01, xend = 525, yend = 4, color='Stim Turn Off'))+
    geom_smooth(method = "loess", se=F)+
    facet_wrap(MVC_Stim~MVC_Voli)+
    labs(x = "Frames",
       y = "Normalized MAV",
       title = "Droping 4 Consecutive Frames",
       subtitle = SubTitleString)+
    ylim(0,1)
plt
#dev.off()

```
```{r}

group_by(Education) %>%summarise(min = min(SBP), Q1 = quantile(SBP, 0.25), median = median(SBP),
Q3 = quantile(SBP, 0.75), max = max(SBP),
mean = mean(SBP), sd = sd(SBP), n = n(), missing = sum(is.na(SBP)))

```


```{r deviding the dropped frames in two way cat.  }
tests <- c("mar7", "mar16",'feb27')
filt='GS'
reps=c('Rep_1','Rep_2','Rep_3')

df<-df%>%mutate(Divide_Cat=recode(Drp_Order,
                                '1st_Dropped' = '1st_Half',
                                '2nd_Dropped' = '1st_Half',
                                '3rd_Dropped' = '2nd_Half',
                                '4th_Dropped' = '2nd_Half'))

TestString<-""
for (iTest in 1:length(tests)) 
{
  TestString<-sprintf("%s, %s",TestString, tests[iTest])
}

RepString<-""
for (iTest in 1:length(reps)) 
{
  RepString<-sprintf("%s, %s",RepString, reps[iTest])
}

SubTitleString<-sprintf("Tests: %s | Repeats: %s | Filter: %s | Dropped Frames are not Filtered" ,TestString,RepString,filt)

plot_df<-filter(df, Test==tests & Repeat==reps & Filt_Type== filt | Filt_Type=='Dropped')
summary (plot_df)

ggplot(plot_df, aes(x = Frame, y = Norm_Val, color = Divide_Cat)) +
    geom_point() +
    geom_line(data= filter(df,Test==tests & Repeat=="Rep_1"& Filt_Type==c("Unfilt")), aes(x = Frame, y = Target*5, color = "Target (a.u.)")) +
    geom_segment(aes(x = 350, y = 1, xend = 525, yend = 1, linetype='dashed', color='Avg. 0-Stim Level'))+
    geom_segment(aes(x = 525, y = 0.01, xend = 525, yend = 4,  linetype='dashed',color='Stim Turn Off'))+
    geom_smooth(method = "loess", se=F)+
    facet_wrap(MVC_Stim~MVC_Voli)+
    labs(x = "Frames",
       y = "Normalized MAV",
       title = "Droping 4 Consecutive Frames",
       subtitle = SubTitleString)+
    ylim(0,7)

#dev.off()
```


```{r Non Normalized values }
tests <- c("mar7","mar16")
filt<-c('GS')
reps<-c('Rep_1','Rep_2','Rep_3')

TestString<-""
for (iTest in 1:length(tests)) 
{
  TestString<-sprintf("%s, %s",TestString, tests[iTest])
}

RepString<-""
for (iTest in 1:length(reps)) 
{
  RepString<-sprintf("%s, %s",RepString, reps[iTest])
}

SubTitleString<-sprintf("Tests: %s | Repeats: %s | Filter: %s | Dropped Frames are not Filtered" ,TestString,RepString,filt)
plot_df<-filter(df, Test==tests)
plot_df<-filter(plot_df, Repeat==reps & Filt_Type==filt | Filt_Type=='Dropped' )

summary(plot_df)

ggplot(plot_df, aes(x = Frame, y = Frame_Val, color = Divide_Cat)) +
    geom_point() + #size = 1.2, alpha = 0.6
    geom_line(data= filter(df,Test==tests & Filt_Type==c("Unfilt")), aes(x = Frame, y = Target*5/35000, color = "Target (a.u.)")) +
    geom_segment(aes(x = 350, y = 1/35000, xend = 525, yend = 1/35000, color='Avg. 0-Stim Level'))+
    geom_segment(aes(x = 525, y = 0.01/35000, xend = 525, yend = 4/35000, color='Stim Turn Off'))+
    geom_smooth(method = "loess", se=F)+
    facet_wrap(MVC_Stim~MVC_Voli)+
    labs(x = "Frames",
       y = "MAV",
       title = "Droping 4 Consecutive Frames",
       subtitle = SubTitleString)+
    ylim(0,0.0002)

#pdf("figures/4dropped3.pdf")

#dev.off()

```

```{r plotting with boxplots}

tests <- c("mar16","mar7")
filt='GS'
reps=c('Rep_1','Rep_2','Rep_3')

TestString<-""
for (iTest in 1:length(tests)) 
{
  TestString<-sprintf("%s, %s",TestString, tests[iTest])
}

RepString<-""
for (iTest in 1:length(reps)) 
{
  RepString<-sprintf("%s, %s",RepString, reps[iTest])
}

median_cl_boot <- function(x, conf = 0.95) {
    lconf <- (1 - conf)/2
    uconf <- 1 - lconf
    require(boot)
    bmedian <- function(x, ind) median(x[ind])
    bt <- boot(x, bmedian, 1000)
    bb <- boot.ci(bt, type = "perc")
    data.frame(y = median(x), ymin = quantile(bt$t, lconf), ymax = quantile(bt$t, 
        uconf))
}

SubTitleString<-sprintf("Tests: %s | Repeats: %s |  Filter for NonDropped: %s | 350<=Frames<=525" ,TestString,RepString,filt)

plot_df<-filter(df, Test==tests & Repeat==reps & Frame <= 525 &  Frame >= 350 & Filt_Type==filt | Filt_Type=='Dropped' )

ggplot(data = plot_df, aes(x = Drp_Order , y = Norm_Val, color = Drp_Order)) + 
  geom_boxplot(notch = TRUE) +
  #geom_segment(aes(x = "NonDropped", y = 1, xend = "4th_Dropped", yend = 1,  color='Avg. 0-Stim Level'))+
  #geom_smooth(method = "loess", se=F)+
  facet_wrap(MVC_Stim~MVC_Voli)+
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar") + 
  stat_summary(fun.y = mean, geom = "point")+
  #stat_summary(fun.data = median_cl_boot, geom = "errorbar", 
  #colour = "red") + stat_summary(fun.y = median, geom = "point", colour = "red")
  labs(x = "Frames",
       y = "Normalized MAV",
       title = "Comparing Dropped Frames using BoxPlots",
       subtitle = SubTitleString)+
  ylim(0,4)
```

```{r plotting with boxplots}

tests <- c("mar16","mar7")
filt='GS'
reps=c('Rep_1','Rep_2','Rep_3')

TestString<-""
for (iTest in 1:length(tests)) 
{
  TestString<-sprintf("%s, %s",TestString, tests[iTest])
}

RepString<-""
for (iTest in 1:length(reps)) 
{
  RepString<-sprintf("%s, %s",RepString, reps[iTest])
}

median_cl_boot <- function(x, conf = 0.95) {
    lconf <- (1 - conf)/2
    uconf <- 1 - lconf
    require(boot)
    bmedian <- function(x, ind) median(x[ind])
    bt <- boot(x, bmedian, 1000)
    bb <- boot.ci(bt, type = "perc")
    data.frame(y = median(x), ymin = quantile(bt$t, lconf), ymax = quantile(bt$t, 
        uconf))
}

SubTitleString<-sprintf("Tests: %s | Repeats: %s |  Filter for NonDropped: %s | 350<=Frames<=525" ,TestString,RepString,filt)

plot_df<-filter(df, Test==tests & Repeat==reps & Frame <= 525 &  Frame >= 350 & Filt_Type==filt | Filt_Type=='Dropped' )

ggplot(data = plot_df, aes(x = Divide_Cat , y = Norm_Val, color = Divide_Cat)) + 
  geom_boxplot(notch = TRUE) +
  #geom_segment(aes(x = "NonDropped", y = 1, xend = "2nd_Half", yend = 1,  color='Avg. 0-Stim Level'))+
  #geom_smooth(method = "loess", se=F)+
  facet_wrap(~MVC_Voli)+
  stat_summary(fun.data = mean_cl_boot, geom = "errorbar") + 
  stat_summary(fun.y = mean, geom = "point")+
  #stat_summary(fun.data = median_cl_boot, geom = "errorbar", 
  #colour = "red") + stat_summary(fun.y = median, geom = "point", colour = "red")
  labs(x = "Frames",
       y = "Normalized MAV",
       title = "Comparing Dropped Frames using BoxPlots",
       subtitle = SubTitleString)+
  ylim(0,4)
```


```{r Stats: Linear Model }

filt_variables<- filter(test_jan7, Filt_Type==c('Dropped', 'Comb' ,'GS'))
model_one <- lm(Norm_Val ~ Filt_Type, data = filt_variables) 

tidy(model_one, conf.int = 0.90) %>% select(term, estimate, std.error,
conf.low, conf.high, p.value) %>% kable(dig = 2)

glance(model_one) %>% select(r.squared) %>% kable(digits = 3)

model_one <- lm(Norm_Val ~ Filt_Type, data = filt_variables) 

```




```{r}
library(ggplot2)
library(EnvStats)

mtcars2 <- mtcars %>% 
  group_by(cyl, am) %>% mutate(n = n()) %>% 
  mutate(label = paste0(cyl,' [N = ',n,']'))

ggplot(mtcars2,
   aes(x = factor(label), y = mpg, color = factor(label))) + 
  geom_point() + 
  facet_wrap(~am, scales = 'free_x') +
  #theme(legend.position = "none")+
  xlab('cyl') 
```
```{r}
library(ggplot2)
library(EnvStats)

p <- ggplot(mtcars, 
  aes(x = factor(cyl), y = mpg, color = factor(cyl))) + 
  theme(legend.position = "none")

p + geom_point() + 
  stat_n_text() + 
  labs(x = "Number of Cylinders", y = "Miles per Gallon")
```



```{r}
#result_df <- aggregate(dt_means$Filt_Mean_Val, by = list(Filt_Type = dt_means$Filt_Type, MVC_Voli = dt_means$MVC_Voli, MVC_Stim = dt_means$MVC_Stim), 
#                         Filt_Type <- as.character(unique(dt_means$Filt_Type[dt_means$Filt_Mean_Val %in% x]))
 #                        reference_value <- ref_dt$Filt_Mean_Val%>% group_by(Filt_Type)
#                         rmse(x, reference = reference_value)
#})

```

```{r}

rmse <- function(x, reference) {
  sqrt(mean((x - reference)^2))
}

percent_diff <- function( mav_f, mav_d) {
  mean(mav_f-mav_d ) / mav_d * 100
}

dt_means <- aggregate(dt$Norm_Val, by = list(Trial = dt$Trial, Test = dt$Test, Filt_Type = dt$Filt_Type, MVC_Voli = dt$MVC_Voli, MVC_Stim = dt$MVC_Stim,Dropped = dt$Dropped), mean)
dt_means <- dt_means %>% rename(Filt_Mean_Val = x)

ref_dt <-dt_means %>% filter(Filt_Type=='Dropped')

dt_means<- dt_means%>%group_by(Filt_Type ) %>% mutate(percent_diff = percent_diff(Filt_Mean_Val,mav_d=filter(dt_means,Filt_Type=='Dropped') $ Filt_Mean_Val))%>%
  group_by(Filt_Type )%>% mutate(rmse = rmse(Filt_Mean_Val,reference=filter(dt_means,Filt_Type=='Dropped') $ Filt_Mean_Val))
dt_means

```

```{r Quick Look}

ggplot(df, aes(x = "", y = Norm_Val)) + geom_violin() + geom_boxplot(width = 0.4) + coord_flip() + labs(x = "")

```

