---
title: "occ_statics"
output: html_document
date: "2023-03-25"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r including libraries, display=FALSE}
library(magrittr); 
library(here); 
library(janitor)
library(readxl);
library(tidyverse)
library(rmdformats)
library(Epi)
library(vcd)
library(broom)
library(patchwork)
library(vcd)
library(dplyr)
library(ggplot2)
```


```{r Data Inject } 

occraw<- read_csv("occlusion.csv",show_col_types = FALSE)
occraw<-occraw[,-7]

occraw

```

```{r dataframe modifications}

occ<-occraw%>%mutate(Test = as.factor(Test),
                     MVC_Voli = as.factor(MVC_Voli),
                     MVC_Stim = as.factor(MVC_Stim),
                     Tau = as.factor(Tau))

occ<-occ%>%mutate(MVC_Voli=recode(MVC_Voli,
                                '10' = 'Voli_10',
                                '20' = 'Voli_20',
                                '30' = 'Voli_30',
                                '40' = 'Voli_40')) %>%
            mutate(MVC_Stim=recode(MVC_Stim,
                                 '0' = 'Stim_0',
                                '10' = 'Stim_10',
                                '20' = 'Stim_20',
                                '30' = 'Stim_30'))

occ<-occ%>%filter(Test!="mar7",Test!="mar16")
summary(occ)

```


```{r  calculating mean occlusion}
selected_tau='3*tau'
selected_test='jan7'

mean_occ<- filter(occ,Tau==selected_tau, Test==selected_test,MVC_Stim!="Stim_0") %>% group_by( MVC_Voli, MVC_Stim) %>% summarise( Mean_F_vprime=round(mean(F_vprime_mvc),3), Std_F_vprime=round(sd(F_vprime_mvc),3), Mean_F_occ=round(mean(F_occ_mvc),3), Std_F_occ=round(sd(F_occ_mvc),3), n = n())
mean_occ

mean_occ_mvc <- filter(occ,Tau==selected_tau,MVC_Stim!="Stim_0") %>% group_by( MVC_Voli, MVC_Stim) %>% summarise( Mean_F_vprime_mvc=round(mean(F_vprime_mvc),3), Std_F_vprime_mvc=round(sd(F_vprime_mvc),3), Mean_F_occ_mvc=round(mean(F_occ_mvc),3), Std_F_occ_mvc=round(sd(F_occ_mvc),3), n = n())
mean_occ_mvc

#mosaic::favstats( F_vprime_mvc~ selected_tau, MVC_Voli, data = occ)%>% knitr::kable(digits = 2)

```

```{r Plotting the results }

plot_tibble<-filter(occ,MVC_Stim!="Stim_0",Tau=="3*tau")

ggplot(plot_tibble, aes(x =  F_v_mvc , y = F_vprime_mvc , color = MVC_Stim)) +
    geom_point() +
    geom_smooth(method = "lm")
#    facet_wrap(MVC_Stim~MVC_Voli)+
   # labs(x = "F_v",
     #  y = "F_vprime",
   #    title = "Droping 4 Consecutive Frames",
    #   subtitle = 'TestString')

```
```{r Plotting the results }

plot_tibble<-filter(occ,MVC_Stim!="Stim_0",Tau=="3*tau")

ggplot(plot_tibble, aes(x =  F_v_mvc, y = F_occ_mvc, color = MVC_Stim)) +
    geom_point() +
    geom_smooth(method = "lm")
```

```{r Occlusion Heat Map}

plot_tibble<-filter(occ,MVC_Stim!="Stim_0",Tau=="3*tau")

ggplot(plot_tibble, aes(x =  MVC_Voli, y = MVC_Stim, fill = F_occ_mvc)) +
  geom_tile() 
  #facet_wrap(~Test)
```

```{r}

plot_tibble<-filter(occ,MVC_Stim!="Stim_0",Tau=="3*tau")

ggplot(plot_tibble, aes(x =  F_v, y = F_occ, color = MVC_Stim))+
  geom_point()+
  geom_smooth(method = "lm")+
  facet_wrap(~Test)
```

```{r Occlusion Heat Map}

plot_tibble<-filter(occ,MVC_Stim!="Stim_0",Tau=="3*tau")

ggplot(plot_tibble, aes(x =  MVC_Voli, y = MVC_Stim, fill = F_occ)) +
  geom_tile() +
  facet_wrap(~Test)

```

```{r  averaging the occlusion }

mn<-aggregate(cbind(F_occ,F_occ_mvc,F_vprime,F_vprime_mvc) ~ Test + MVC_Stim + MVC_Voli , data = filter(occ,Tau==selected_tau), FUN = mean, na.rm = TRUE)

sdt<-aggregate(cbind(F_occ,F_occ_mvc,F_vprime,F_vprime_mvc) ~ Test + MVC_Stim + MVC_Voli, data = filter(occ,Tau==selected_tau), FUN = sd, na.rm = TRUE)


occ_mean <- aggregate(data=occ, cbind(F_occ,F_occ_mvc), by = list(Test = occ$Test, 
                                             MVC_Stim = occ$MVC_Stim, 
                                             MVC_Voli = occ$MVC_Voli, 
                                             Tau = occ$Tau), mean)
occ_mean <- occ_mean %>% rename(F_occ_mean = x)

occ_sd <- aggregate(occ$F_occ, by = list(Test = occ$Test, 
                                             MVC_Stim = occ$MVC_Stim, 
                                             MVC_Voli = occ$MVC_Voli, 
                                             Tau = occ$Tau), sd)
occ_mean$f_occ_sd<-occ_sd$x

occ_mean_mvc <- aggregate(occ$F_occ_mvc, by = list(Test = occ$Test, 
                                             MVC_Stim = occ$MVC_Stim, 
                                             MVC_Voli = occ$MVC_Voli, 
                                             Tau = occ$Tau), mean)

occ_mean_mvc <- occ_mean_mvc %>% rename(F_occ_mvc_mean = x)

occ_sd_mvc <- aggregate(occ$F_occ_mvc, by = list(Test = occ$Test, 
                                             MVC_Stim = occ$MVC_Stim, 
                                             MVC_Voli = occ$MVC_Voli, 
                                             Tau = occ$Tau), sd)

occ_mean_mvc$F_occ_mvc_sd<-occ_sd_mvc$x

occ_mean$F_occ_mvc_mean<-occ_mean_mvc$F_occ_mvc_mean
occ_mean$F_occ_mvc_sd<-occ_mean_mvc$F_occ_mvc_sd

mean_occ_tbl <- occ_mean %>% group_by( MVC_Voli, MVC_Stim) %>% summarise(mean_occ_mvc=round(mean(F_occ_mvc_mean),2), Std=round(sd(F_occ_mvc_mean),2), mean_F_vprime_mvc=round(mean(F_occ_mvc_mean),2), Std=round(sd(F_occ_mvc_mean),2), n = n())

mean_occ_tbl

```

```{r }
df%>% mutate(bmi_cat = fct_reorder(bmi_cat, triceps_skinfold,.fun = median)) 

df %>% group_by(Test) %>% summarise("Pearson r" = round(cor(TimeConst, MVC_Percent, use="complete"),2), "Spearman r" = round(cor(TimeConst, MVC_Percent, method="spearman",use="complete"),2), "Mean"= round(mean(TimeConst),2))

```

```{r }
plot<-filter(dt)%>% select( c(Frame_Val,Norm_Val, Target, Filt_Type, Dropped,Frame,Test,MVC_Voli,MVC_Stim) )  

mosaic::favstats( Norm_Val~ Filt_Type, MVC_Voli, data = plot)%>% knitr::kable(digits = 2)

ggplot(data = plot, aes(x = Dropped , y = Norm_Val, color = Filt_Type)) + 
geom_boxplot() +
  scale_fill_viridis_d() +
  facet_wrap(Test~ MVC_Voli )+
labs(title = "Normalized EMG MAV Values", y = "Norm. MAV")
   
```







