---
title: "Occlusion Est Error"
output: html_document
date: "2023-09-06"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r including libraries, display=FALSE}
library(magrittr); 
library(here); 
library(janitor)
library(readxl);
library(tidyverse)
library(rmdformats)
library(Epi)
library(vcd)
library(broom)
library(patchwork)
library(vcd)
library(dplyr)
library(ggplot2)
library(ggsignif)

```



```{r Data Inject } 

err_raw<- read_csv("occ_est_error6.csv",show_col_types = FALSE)
err_raw

droppedocc<- read_csv("dropped_occ.csv",show_col_types = FALSE)
droppedocc

```



```{r dataframe modifications}


err<-err_raw%>%mutate(MVC_Voli_Cat=recode(VoliMVC,
                                '10' = 'Voli_10',
                                '20' = 'Voli_20',
                                '30' = 'Voli_30',
                                '40' = 'Voli_40')) %>%
            mutate(MVC_Stim_Cat=recode(StimMVC,
                                 '0' = 'Stim_0',
                                '10' = 'Stim_10',
                                '20' = 'Stim_20',
                                '30' = 'Stim_30'))

err<-err%>%mutate(Test = as.factor(Test),
                     Filt = as.factor(Filt),
                     Occ_Type = as.factor(Occ_Type),
                     MVC_Stim_Cat = as.factor(MVC_Stim_Cat),
                     MVC_Voli_Cat = as.factor(MVC_Voli_Cat),
                     MVC_Stim = as.integer(StimMVC),
                      MVC_Voli = as.integer(VoliMVC))

err_raw<-err%>%filter(Test!="mar7",Test!="mar16",Test!="feb27",Test!="apr20")
summary(err)




droppedocc<-droppedocc%>%mutate(MVC_Voli_Cat=recode(VoliMVC,
                                '10' = 'Voli_10',
                                '20' = 'Voli_20',
                                '30' = 'Voli_30',
                                '40' = 'Voli_40')) %>%
            mutate(MVC_Stim_Cat=recode(StimMVC,
                                 '0' = 'Stim_0',
                                '10' = 'Stim_10',
                                '20' = 'Stim_20',
                                '30' = 'Stim_30'))


droppedocc<-droppedocc%>%mutate(Test = as.factor(Test),
                     StimMVC = as.integer(StimMVC),
                     VoliMVC = as.integer(VoliMVC),
                     MVC_Voli_Cat = as.factor(MVC_Voli_Cat),
                     MVC_Stim_Cat = as.factor(MVC_Stim_Cat),
                     Repeat = as.factor(Repeat),
                     NumofDropped = as.factor(NumofDropped))
droppedocc<-droppedocc%>%filter(Test!="mar7",Test!="mar16",Test!="feb27",Test!="apr20")


```


```{r Plotting: maintain section  }
filt="GS"
occ_err<-filter(err, MVC_Stim_Cat!="Stim_0",Filt==filt, Occ_Type=='Occ_mvc')

occ_err1<-filter(err, MVC_Stim_Cat!="Stim_0")

p1<-ggplot(occ_err, aes(x =  VoliMVC , y = Effort_e_Amp_err , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 10, y = 0, xend = 40, yend = 0, color='Zero Error'))+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Effort Estimation Error before Occlusion Correction",
    subtitle = sprintf('%s filtered results',filt))

p2<-ggplot(occ_err, aes(x =  VoliMVC , y = Effort_Amp_err , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 10, y = 0, xend = 40, yend = 0, color='Zero Error'))+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Effort Estimation Error after Occlusion Correction",
    subtitle = sprintf(' %s filtered results',filt))

p3<-ggplot(occ_err1, aes(x =  VoliMVC , y = Effort_Amp_err , color = Filt)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 10, y = 0, xend = 40, yend = 0, color='Zero Error'))+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "",
    subtitle = " Comparing Different Filters")
p1/p2 -p3


```
```{r Individualized occ errors}
filt="GS"
occ_err<-filter(err, MVC_Stim_Cat!="Stim_0",Filt==filt, Occ_Type=='Occ_mvc')

occ_err1<-filter(err, MVC_Stim_Cat!="Stim_0")

p1<-ggplot(occ_err, aes(x =  VoliMVC , y = Effort_e_Amp_err , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    ylim(-55, 25)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Effort Estimation Error before Occlusion Correction",
    subtitle = sprintf('%s filtered results',filt))

p2<-ggplot(occ_err, aes(x =  VoliMVC , y = Effort_Amp_Indv_err , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    ylim(-55, 25)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Effort Estimation Error Using Individual Occlusion Correction",
    subtitle = sprintf(' %s filtered results',filt))

p3<-ggplot(occ_err, aes(x =  VoliMVC , y = Effort_Amp_err , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    ylim(-55, 25)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Effort Estimation Error Using Averaged Occlusion Correction",
    subtitle = sprintf('%s filtered results',filt))
mean_err<-occ_err %>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_e_Amp_err),2), "RMS"=round(sqrt(mean(Effort_e_Amp_err^2)),2),"Est"='Before Correction') 
mean_err<-mean_err%>%add_row(occ_err %>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_Indv_err),2), "RMS"=round(sqrt(mean(Effort_Amp_Indv_err^2)),2),"Est"='Individualized Correction') )
mean_err<-mean_err%>%add_row(occ_err %>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_err),2), "RMS"=round(sqrt(mean(Effort_Amp_err^2)),2),"Est"='After Correction') )

p4<-ggplot(mean_err, aes(x =  Est , y = Mean , color = Est)) +
    geom_boxplot(notch = FALSE) +
    #geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    ylim(-20, 20)+
    facet_wrap( ~ MVC_Voli_Cat)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Mean",
    subtitle = sprintf('%s filtered results',filt))
p5<-ggplot(mean_err, aes(x =  Est , y = RMS , color = Est)) +
    geom_boxplot(notch = FALSE) +
    #geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    facet_wrap( ~ MVC_Voli_Cat)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "RMS",
    subtitle = sprintf('%s filtered results',filt))
p1/p2/p3-p4/p5
```

```{r occ errors of different methods }
filt="GS"
occ_err<-filter(err, MVC_Stim_Cat!="Stim_0",Filt==filt)

ggplot(occ_err, aes(x =  VoliMVC)) +
  geom_point(aes( y = Effort_e_Amp_err, color='Before Correction')) +
  geom_point(aes( y = Effort_Amp_err, color='After Correction')) +
  geom_point(aes( y = Effort_Amp_Indv_err, color='Indiv. Correction')) +
  geom_smooth(aes(y = Effort_e_Amp_err, color='Before Correction'), method = "lm") +
  geom_smooth(aes(y = Effort_Amp_err, color='After Correction'), method = "lm")+
  geom_smooth(aes( y = Effort_Amp_Indv_err, color='Indiv. Correction'), method = "lm")+
  geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
  facet_wrap(~Occ_Type)
```

```{r }
filt="GS"
type='Occ_Hybrid_mvc'
Log=FALSE
occ_err<-filter(err, MVC_Stim_Cat!="Stim_0",Filt==filt, Occ_Type!=type,LogModel==Log)%>%
  select(Occ_Type,Effort_Amp_err,Effort_e_Amp_err,MVC_Stim_Cat,VoliMVC)
occ_err_wide<-occ_err %>% pivot_wider(names_from = Occ_Type, values_from = Effort_Amp_err)

occ_err_long<-occ_err_wide%>%pivot_longer(cols=c('Occ_mvc','Occ_Dropped_mvc','Effort_e_Amp_err'),
                                    names_to='Occ_Error_Type',
                                    values_to='Error')
#%>%mutate(Occ_Error_Type=recode(
 #                                     Occ_Error_Type,'Occ_mvc' = 'Force Based',
  #                                    'Occ_Dropped_mvc' = 'Dropped Frames\nBased',
   #                                   'Effort_e_Amp_err' = 'Before Correction'))

occ_err1<-filter(err, MVC_Stim_Cat!="Stim_0",Occ_Type=="Occ_mvc")

p1<-ggplot(occ_err_long, aes(x =  VoliMVC , y = Error , color = MVC_Stim_Cat)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    facet_wrap(~Occ_Error_Type)+
    ylim(-50, 20)+
    labs(x = "Volitional Effort: E_v (% Effort)",
    y = "Effort Estimation Error (% Effort)",
    subtitle = sprintf('                      (a)                                             (b)                                           (c)',type, filt))+
    scale_color_hue(labels=c('10% Stim', '20% Stim', '30% Stim','Zero Error'),name="Stimulated \nEffort Levels")+
  theme(legend.position = c(0.92, 0.3))


p2<-ggplot(occ_err_long, aes(x =  Occ_Error_Type , y = Error,color=Occ_Error_Type )) +
    geom_boxplot(notch=TRUE)+
    ylim(-55, 25)+
    geom_signif(comparisons = list(c("Before Correction","Dropped Frames\nBased")), 
                y_position = 10, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    geom_signif(comparisons = list(c("Dropped Frames\nBased","Force Based")),
                y_position = 14, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("**"),color = "black")+
    geom_signif(comparisons = list(c("Before Correction","Force Based")), 
                y_position = 17, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    labs(x = "Volitional Effort: E_v (% Effort)",
    y = "Effort Estimation Error (% Effort)",
     subtitle = "                               (d)  ")+
    scale_color_hue(labels=c('Before Correction', 'Dropped Frames\nBased', 'Force Based'),name="Correction")+
    theme(legend.position = c(0.8, 0.2))

p3<-ggplot(occ_err1, aes(x =  Filt , y = Effort_Amp_err , color = Filt)) +
    geom_boxplot(notch=TRUE)+
    #geom_smooth(method = "lm")+ 
   # geom_segment(aes(x = 10, y = 0, xend = 40, yend = 0, color='Zero Error'))+
    ylim(-50, 50)+
    geom_signif(comparisons = list(c("Comb","Unfilt")), 
                y_position = 40, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    geom_signif(comparisons = list(c("GS","Comb")),
                y_position = 35, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black")+
    geom_signif(comparisons = list(c("Unfilt","GS")), 
                y_position = 30, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    labs(x = "Volitional Effort: E_v (% Effort)",
    y = "Effort Estimation Error (% Effort)",
    #title = "",
    subtitle = "                               (e)")+
    #scale_color_hue(labels=c('Comb', 'GS', 'Unfiltered'),name="Filter")+
    theme(legend.position = c(0.8, 0.2))

#pdf("conf2.pdf") 

suppressWarnings(print(p1/(p2-p3)))

#dev.off()

mean_err_type<-occ_err_long %>% group_by(Occ_Error_Type)  %>% summarise( "Mean"= round(mean(Error),2), "RMS"=round(sqrt(mean(Error^2)),2),"Est"='Before Correction') 

#mean_err<-mean_err%>%add_row(occ_err %>% filter(LogModel==Log)%>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_Indv_err),2), "RMS"=round(sqrt(mean(Effort_Amp_Indv_err^2)),2),"Est"='Individualized Correction',"Log"=Log) )

#mean_err<-mean_err%>%add_row(occ_err %>% filter(LogModel==Log) %>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_err),2), "RMS"=round(sqrt(mean(Effort_Amp_err^2)),2),"Est"='After Correction',"Log"=Log) )

```

```{r }
library(egg)

filt="GS"
type='Occ_mvc'
Log=FALSE
occ_err<-filter(err, EffortType=="Force", MVC_Stim_Cat!="Stim_0", Occ_Type==type, LogModel==Log)%>%
  select(Occ_Type,Effort_Amp_err,Effort_e_Amp_err,MVC_Stim_Cat,VoliMVC,Filt)

occ_err_wide<-occ_err %>% pivot_wider(names_from = Occ_Type, values_from = Effort_Amp_err)

occ_err_long<-occ_err_wide%>%pivot_longer(cols=c('Occ_mvc','Effort_e_Amp_err'),
                                    names_to='Occ_Error_Type',
                                    values_to='Error')%>%mutate(Occ_Error_Type = as.factor(Occ_Error_Type))



occ_err1<-filter(err, EffortType=="Force", MVC_Stim_Cat!="Stim_0", Occ_Type==type, LogModel==Log)

occ_err_long <- occ_err_long %>%
  mutate(Occ_Error_Type = relevel(Occ_Error_Type, ref = "Effort_e_Amp_err"))

#my_labeller <- as_labeller(c(Occ_mvc="E[o]+E[e]", Effort_e_Amp_err="E[e]", Occ_Dropped_mvc="E[d]+E[e]"),
 #                         default = label_parsed)

my_labeller <- as_labeller(c(Occ_mvc="Corrected", Effort_e_Amp_err="Uncorrected"),
                           default = label_parsed)

occ_err_long1<-filter(occ_err_long, Filt==filt)

p1<-ggplot(occ_err_long1, aes(x =  VoliMVC , y = Error+5 , color = MVC_Stim_Cat)) +
    geom_point( size = 3) +
    geom_smooth(method = "lm", size = 2,se = FALSE)+ 
    geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    facet_wrap(~Occ_Error_Type,labeller=my_labeller)+
    ylim(-50, 25)+
    #annotate("text", x=0.5, y=20, label= "(a)", size=6)+
    labs(x = expression("Volitional Effort (V) "),
    y = "Estimation Error (% Effort)",
    #subtitle = sprintf('                          (a)                                                      (b)                           ',type, filt)
    )+
    scale_color_hue(labels=c('10% Stim', '20% Stim', '30% Stim','Zero Error'),name=expression("Stim. Effort (S)"))+
    theme_minimal(base_size = 17) +
  theme(
    strip.background = element_blank(),
    legend.position = c(0.6, 0.25),
    legend.background = element_rect(fill = alpha("white", 0.6)))
p1<-tag_facet(p1, size= 6,hjust = -1)



occ_err_long1<-occ_err_long1%>%mutate(Occ_Error_Type=recode(Occ_Error_Type,
                                             'Effort_e_Amp_err' = 'Uncorrected',
                                             'Occ_mvc' = 'Occlusion Corrected'
  ))

p2<-ggplot(occ_err_long1, aes(x =  Occ_Error_Type , y = Error+7, color=Occ_Error_Type )) +
  geom_boxplot(notch=TRUE)+
  geom_jitter(width = 0.2, alpha = 0.5, size = 3) +  # Add scatter points with jitter
  ylim(-50, 40)+
  annotate("text", x=0.55, y=32, label= "(c)", size=6,fontface = "bold") +  
  geom_signif(comparisons = list(c("Uncorrected","Occlusion Corrected")), 
                y_position = 15, tip_length = 0.02, vjust = 0.1, size = 0.8, textsize = 8, map_signif_level=TRUE,annotation = c("*"),color = "black") +

  labs(x = NULL,
  y = "Estimation Error (% Effort)")+
  #subtitle = "                           (c)  ")+
  scale_color_hue(labels=c('Uncorrected', 'Corrected'),name="Correction \nMethods")+
    theme_minimal(base_size = 17) +
  theme(
    strip.background = element_blank(),
    legend.position = c(0.8, 0.2),
    legend.background = element_rect(fill = alpha("white", 0.6)))

occ_err_long2<-filter(occ_err_long, Occ_Error_Type=="Occ_mvc")

p3<-ggplot(occ_err_long2, aes(x =  Filt , y = Error+7, color = Filt)) +
    geom_boxplot(notch=TRUE)+
    geom_jitter(width = 0.2, alpha = 0.5, size = 3) +  # Add scatter points with jitter
    #geom_smooth(method = "lm")+ 
    #geom_segment(aes(x = 10, y = 0, xend = 40, yend = 0, color='Zero Error'))+
    ylim(-50, 40)+
    annotate("text", x=0.55, y=32, label= "(d)", size=6,fontface = "bold") +  
    geom_signif(comparisons = list(c("Comb","Unfilt")), 
                y_position = 40, tip_length = 0.02, vjust = 0.1,size = 0.5, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    geom_signif(comparisons = list(c("GS","Comb")),
                y_position = 35, tip_length = 0.02, vjust = 0.1, map_signif_level=TRUE,annotation = c("*"),color = "black")+
    geom_signif(comparisons = list(c("Unfilt","GS")), 
                y_position = 15, tip_length = 0.01, vjust = 0.1, size = 0.8, textsize = 8, map_signif_level=TRUE,annotation = c("*"),color = "black") +
    labs(x = NULL,
    y = NULL) + # Removes y-axis labels
    #title = "",
    #subtitle = "                        (d)")+
    scale_color_hue(labels=c('Comb', 'GS', 'Unfiltered'),name="Filter")+
    theme_minimal(base_size = 17) +
    theme(
    strip.background = element_blank(),
    legend.position = c(0.8, 0.2),
    legend.background = element_rect(fill = alpha("white", 0.6)),
    axis.text.y = element_blank(),  # Removes y-axis text
    axis.ticks.y = element_blank() # Removes y-axis ticks
  )


#pdf("occ_err_embc2.pdf", width = 8, height = 8)  # specify dimensions in inches

suppressWarnings(print(p1/(p2-p3)))

#dev.off()

#anova(lm(Error ~ Occ_Error_Type, data =  occ_err_long))
#TukeyHSD(aov(Error ~ Occ_Error_Type, data = occ_err_long))

#anova(lm(Effort_Amp_err ~ Filt, data =  occ_err1))
#TukeyHSD(aov(Effort_Amp_err ~ Filt, data = occ_err1))


#mean_err_type<-occ_err_long %>% group_by(Occ_Error_Type)  %>% summarise( "Mean"= round(mean(Error),2), "RMS"=round(sqrt(mean(Error^2)),2),"Est"='Before Correction') 

#mean_err<-mean_err%>%add_row(occ_err %>% filter(LogModel==Log)%>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_Indv_err),2), "RMS"=round(sqrt(mean(Effort_Amp_Indv_err^2)),2),"Est"='Individualized Correction',"Log"=Log) )

#mean_err<-mean_err%>%add_row(occ_err %>% filter(LogModel==Log) %>% group_by(MVC_Voli_Cat) %>% summarise( "Mean"= round(mean(Effort_Amp_err),2), "RMS"=round(sqrt(mean(Effort_Amp_err^2)),2),"Est"='After Correction',"Log"=Log) )

```


```{r occ errors of different methods }
filt="GS"
occ_err<-filter(err, MVC_Stim_Cat!="Stim_0",Occ_Type=="Occ_mvc",Filt==filt)


p1<-ggplot(occ_err, aes(y = Effort_e_Amp, x =  VoliMVC,color=MVC_Stim_Cat)) +
  geom_point()+
  geom_smooth(method = "lm")
#facet_wrap(~MVC_Stim_Cat)

p2<-ggplot(occ_err, aes(y = Effort_e_Amp_err, x =  VoliMVC,color=MVC_Stim_Cat)) +
  geom_point()+
  geom_smooth(method = "lm")
  #facet_wrap(~Test)
p1/p2
```


```{r faceted by Test}

mean_err<-occ_err %>% group_by(Test) %>% summarise( "Mean"= round(mean(Effort_e_Amp_err),2), "RMS"=round(sqrt(mean(Effort_e_Amp_err^2)),2),"Est"='Before Correction') 
mean_err<-mean_err%>%add_row(occ_err %>% group_by(Test) %>% summarise( "Mean"= round(mean(Effort_Amp_Indv_err),2), "RMS"=round(sqrt(mean(Effort_Amp_Indv_err^2)),2),"Est"='Individualized Correction') )
mean_err<-mean_err%>%add_row(occ_err %>% group_by(Test) %>% summarise( "Mean"= round(mean(Effort_Amp_err),2), "RMS"=round(sqrt(mean(Effort_Amp_err^2)),2),"Est"='After Correction') )

ggplot(mean_err, aes(x =  Est , y = Mean , color = Est)) +
    geom_bar(stat = "identity", position=position_dodge()) +
    #geom_segment(aes(x = 9, y = 0, xend = 41, yend = 0, color='Zero Error'))+
    facet_wrap(~Test)+
    ylim(-40, 20)+
    labs(x = "Volitional Effort: F_v (% MVC)",
    y = "Effort Estimation Error (% MVC)",
    title = "Mean",
    subtitle = sprintf('%s filtered results',filt))

```


```{r linear models}
occ_err_lm<-filter(err, MVC_Stim_Cat!="Stim_0",Filt!="Unfilt" )
occ_err_lm <- occ_err_lm %>%
  mutate(Filt = relevel(Filt, ref = "Comb"))

  m1 <- lm(Effort_Amp_err ~ Filt, data = occ_err_lm) 
tidy(m1,conf.int = TRUE ,conf.level =0.95) %>% knitr::kable(digits = 3)

  m2 <- lm(Effort_Amp_err ~ MVC_Voli_Cat, data = filter(err, MVC_Stim_Cat!="Stim_0",Filt=="GS" )) 
tidy(m2,conf.int = TRUE ,conf.level =0.95) %>% knitr::kable(digits = 3)

```

The average error for GS is -1.5 while Comb filter estimates an average of -1.5+7.6=6.1. a0 and a1 values are -1.5 and 7.6.

Effort estimation error with comb filter is higher with and average of 6.4 compared to GS filter.

```{r Dropped Frames vs Voli only }

ggplot(droppedocc, aes(x =  VoliMVC , y = MAV*100 , color = MAV_Type)) +
    geom_point() +
    geom_smooth(method = "lm")+ 
    facet_wrap(~Test)+
    labs(x = "Volitional Effort Levels : F_v (% MVC)",
    y = "Effort (% MVC)",
    title = "Comparing the Dropped Frames to the Volitional Trials",
    subtitle = sprintf(''))

droppedocc_lm <- filter(droppedocc, MAV_Type == "Occ")
#droppedocc_lm <- droppedocc_lm %>% mutate(MAV_Type = relevel(MAV_Type, ref = "Dropped"))

m1 <- lm(MAV ~ VoliMVC + StimMVC, data = droppedocc_lm) 
tidy(m1,conf.int = TRUE ,conf.level =0.95) %>% knitr::kable(digits = 3)

```


```{r Dropeed frames error }

dropped_err<-filter(droppedocc, NumofDropped =='1_Drops')

p3<-ggplot(dropped_err, aes(x =  VoliMVC , y = Occ_MAV, color = StimMVC))+
  geom_point() +
  geom_smooth(method = "lm",level=0.90) +
  labs(x = "Volitional MVC",
       y = "Occluded Effort (% MVC)",
       title = "Occluded effort from the dropped frames",
       subtitle = "MAV_dropped-MAV_nostim")
#  geom_segment(aes(x = 10, y = 10, xend = 40, yend = 40, color='No Occlusion Level'))+
#      facet_wrap(~Test)
p3

```


```{r linear models }
#dropped_err <- dropped_err %>%
#  mutate(Filt = relevel(Filt, ref = "Comb"))

  m4 <- lm(Occ_MAV ~ MVC_Voli_Cat, data = dropped_err) 
tidy(m4,conf.int = TRUE ,conf.level =0.95) %>% knitr::kable(digits = 3)

```



