---
title: "occ levels"
output: html_document
date: "2024-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r including libraries, display=FALSE}
library(magrittr); 
library(here); 
library(janitor)
library(readxl);
library(tidyverse)
library(rmdformats)
library(Epi)
library(vcd)
library(broom)
library(patchwork)
library(vcd)
library(dplyr)
library(ggpmisc)
library(tidyr)
library(ggsignif)
library(ggplot2)

options(dplyr.summarise.inform = FALSE)

```


```{r Plotting: dropped frames occlusion}
droppedocc<- read_csv("dropped_occ6.csv",show_col_types = FALSE)

droppedocc<-droppedocc%>%mutate(Test = as.factor(Test),
                     Repeat = as.factor(Repeat),
                     NumofDropped = as.factor(NumofDropped))

droppedocc<-droppedocc%>%mutate(MVC_Voli_Cat=recode(MVC_Voli,
                                '10' = 'Voli_10',
                                '20' = 'Voli_20',
                                '30' = 'Voli_30',
                                '40' = 'Voli_40',
                                '50' = 'Voli_50')) %>%
            mutate(MVC_Stim_Cat=recode(MVC_Stim,
                                 '0' = 'Stim_0',
                                '10' = 'Stim_10',
                                '20' = 'Stim_20',
                                '30' = 'Stim_30',
                                '40' = 'Stim_40'))

summary(droppedocc)

plotibble<-filter(droppedocc, NumofDropped !='4_Drops', MAV_Type !='OccHybrid', MAV_Type !='Comb',EffortType=="Hand")
formula <- y ~ poly(x, 1, raw = TRUE)
my.format <-"b[0]~`=`~%.3g*\", \"*b[1]~`=`~%.3g"
p1<-ggplot(plotibble, aes(x =  MVC_Voli , y = MAV, color = MAV_Type))+
  geom_point() +
  geom_smooth(method = "lm",level=0.90)+
  #geom_segment(aes(x = 10, y = 10, xend = 40, yend = 40, color='No Occlusion Level'))+
  ylim(-00, 75)+
  facet_wrap(~MVC_Stim_Cat)

suppressWarnings(print(p1))

#lm_tibble<-filter(plotibble, MAV_Type =='Dropped')

  m1 <- lm(100*MAV ~ MVC_Voli+MVC_Stim+MAV_Type, data = plotibble) 
tidy(m1,conf.int = TRUE ,conf.level =0.95) %>% knitr::kable(digits = 3)

```